name: Test GitHub Secrets

on:
  workflow_dispatch:  # This allows you to run the workflow manually from the GitHub UI

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Test AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Test AWS credentials
        run: |
          echo "Testing AWS credentials..."
          aws ecr describe-repositories --repository-names navnote-frontend navnote-backend
          echo "AWS credentials are working correctly!"
      
      # Test SSH key
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          # Disable strict host key checking for this test
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ec2-user@35.175.178.186 "echo 'SSH connection successful!'" || exit 1